### PR TITLE
Changing Koans to avoid cultural appropriation

### PR DESCRIPTION
**Pull request by CheezItMan**
As per our feedback from a C7 student, I've tried to take out all the zen references and add hiking references to fit with our Seattle location.  It seems to work.

### CODE REVIEW

**Review by tildeee — APPROVED** [review]
Awesome insight and changes!

**Comment by kariabancroft** [comment]
I LOVE the hiking!! Also, your mountain ascii art is spectacular.

I think we should probably just remove the download folder since we don't ever reference it. 

One thing that I'm wondering is if we should really make this most specific to what we need by removing the windows references and other things like that. Some of the external links are actually broken...

**Comment by droberts-ada** [comment]
Line 539 of `neo.rb` contains a blip about "<exercise> has expanded your awareness" - should we change this?

Maybe something like "You have reached the summit of <exercise>"

**Comment by droberts-ada** [comment]
I did download and run your version, and other than the above everything looks good.

**Comment by CheezItMan** [comment]
@kariabancroft I kept the `download` folder just so that they can regen the koans, if they want to start over fresh.  Seemed a shame to lose the functionality.  

I did take out the windows references.

**Comment by CheezItMan** [comment]
@droberts-ada Thanks and fixed!

**Review by droberts-sea — APPROVED** [review]

**Pull request merged**
